-- Phase: n8n automation integration
-- Table: automation_events  (idempotency ledger for inbound/outbound automation events)
--
-- PROPOSED — NOT APPLIED. Written as part of the FlowLead <-> n8n integration branch.
-- `POST /api/automation/result` depends on this table for its idempotency guarantee:
-- it claims an event by inserting the primary key first, so a duplicate delivery of the
-- same event_id loses the race with a 23505 unique violation and is answered as a no-op.
-- Without this table the inbound route degrades to "reject everything" rather than
-- risking a double-write.

-- =============================================================================
-- 1. Enum
-- =============================================================================
CREATE TYPE public.automation_event_status AS ENUM ('processing', 'completed', 'failed');

-- =============================================================================
-- 2. Table
-- =============================================================================
CREATE TABLE public.automation_events (
  -- event_id is generated by the emitting side and is the idempotency key.
  event_id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES public.leads(id) ON DELETE SET NULL,
  direction text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  event_type text NOT NULL,
  status public.automation_event_status NOT NULL DEFAULT 'processing',
  error_message text,
  result_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER automation_events_updated_at BEFORE UPDATE ON public.automation_events
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- 3. Row Level Security
-- =============================================================================
-- Members may read their own org's automation history (for a future audit UI).
-- There are deliberately NO insert/update/delete policies: only the service role,
-- which bypasses RLS, writes here.
ALTER TABLE public.automation_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "automation_events_select" ON public.automation_events FOR SELECT
  USING (app.is_member(organization_id));

-- =============================================================================
-- 4. Indexes
-- =============================================================================
CREATE INDEX idx_automation_events_org_created
  ON public.automation_events(organization_id, created_at DESC);
CREATE INDEX idx_automation_events_lead ON public.automation_events(lead_id);
CREATE INDEX idx_automation_events_status
  ON public.automation_events(organization_id, status);
